# Changes here will be overwritten by Copier
_commit: 5af64c5
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: dev@1kbgz.com
github: 1kbgz
project_description: ccflow models for S3
project_name: ccflow-s3
python_version_primary: '3.11'
team: 1kbgz
