# @package credentials.s3

aws:
  _target_: ccflow_s3.S3ClientCredentials
  mode: env
  access_key_id_env: AWS_ACCESS_KEY_ID
  secret_access_key_env: AWS_SECRET_ACCESS_KEY
  session_token_env: AWS_SESSION_TOKEN
  region_name_env: AWS_REGION
