# @package credentials.s3

cloudflare:
  _target_: ccflow_s3.S3ClientCredentials
  mode: env
  access_key_id_env: CLOUDFLARE_R2_ACCESS_KEY_ID
  secret_access_key_env: CLOUDFLARE_R2_SECRET_ACCESS_KEY
  region_name: auto
